"""001_initial_schema_baseline

Revision ID: 9d11688b7b6a
Revises: 
Create Date: 2026-10-02 11:59:19.896246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d11688b7b6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('masked_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_key_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_configs_id'), ['id'], unique=False)

    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('embedding_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_embeddings_collection_name'), ['collection_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_embeddings_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_embeddings_id'), ['id'], unique=False)

    op.create_table('system_compute_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_gpus', sa.String(), nullable=True),
    sa.Column('allocated_cpu_cores', sa.Integer(), nullable=True),
    sa.Column('memory_limit_gb', sa.Integer(), nullable=True),
    sa.Column('utilization_pct', sa.Integer(), nullable=True),
    sa.Column('scheduler_status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_compute_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_compute_configs_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('compute_quota_gpu_hours', sa.Float(), nullable=True),
    sa.Column('compute_used_gpu_hours', sa.Float(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=True),
    sa.Column('balance_usd', sa.Float(), nullable=True),
    sa.Column('token_quota', sa.Integer(), nullable=True),
    sa.Column('token_used', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=False)

    op.create_table('billing_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_transactions_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('checkpoint_data', sa.JSON(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)

    op.create_table('agent_reach_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('evidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('community_sentiment', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_reach_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_reach_evidence_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_reach_evidence_project_id'), ['project_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('dataset_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dataset_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_recommendations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_recommendations_project_id'), ['project_id'], unique=False)

    op.create_table('experiment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('roadmap', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('hardware_requirements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_plans_project_id'), ['project_id'], unique=False)

    op.create_table('experiment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('metrics_history', sa.JSON(), nullable=True),
    sa.Column('plots', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_runs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_runs_project_id'), ['project_id'], unique=False)

    op.create_table('generated_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_files_project_id'), ['project_id'], unique=False)

    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hypotheses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hypotheses_project_id'), ['project_id'], unique=False)

    op.create_table('knowledge_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_edges_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_edges_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_edges_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_edges_target'), ['target'], unique=False)

    op.create_table('knowledge_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_nodes_type'), ['type'], unique=False)

    op.create_table('literature_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('literature_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_literature_papers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_literature_papers_project_id'), ['project_id'], unique=False)

    op.create_table('research_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('novelty_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('opportunity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_gaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_gaps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_gaps_project_id'), ['project_id'], unique=False)

    op.create_table('research_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('memory_type', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_memory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_memory_memory_type'), ['memory_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_memory_project_id'), ['project_id'], unique=False)

    op.create_table('research_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('stage_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('reasoning_chain', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_stages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_stages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_stages_stage_name'), ['stage_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_stages_status'), ['status'], unique=False)

    op.create_table('scientific_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('publication_readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scientific_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scientific_papers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scientific_papers_project_id'), ['project_id'], unique=False)

    op.create_table('uploaded_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_papers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_papers_project_id'), ['project_id'], unique=False)

    op.create_table('debate_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('proposal_a', sa.Text(), nullable=False),
    sa.Column('proposal_b', sa.Text(), nullable=False),
    sa.Column('proposal_c', sa.Text(), nullable=True),
    sa.Column('debate_rounds', sa.JSON(), nullable=True),
    sa.Column('winner_proposal', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debate_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debate_logs_hypothesis_id'), ['hypothesis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debate_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_debate_logs_project_id'), ['project_id'], unique=False)

    op.create_table('peer_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['scientific_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('peer_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peer_reviews_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_peer_reviews_paper_id'), ['paper_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peer_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peer_reviews_paper_id'))
        batch_op.drop_index(batch_op.f('ix_peer_reviews_id'))

    op.drop_table('peer_reviews')
    with op.batch_alter_table('debate_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debate_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_debate_logs_id'))
        batch_op.drop_index(batch_op.f('ix_debate_logs_hypothesis_id'))

    op.drop_table('debate_logs')
    with op.batch_alter_table('uploaded_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_papers_project_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_papers_id'))

    op.drop_table('uploaded_papers')
    with op.batch_alter_table('scientific_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scientific_papers_project_id'))
        batch_op.drop_index(batch_op.f('ix_scientific_papers_id'))

    op.drop_table('scientific_papers')
    with op.batch_alter_table('research_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_stages_status'))
        batch_op.drop_index(batch_op.f('ix_research_stages_stage_name'))
        batch_op.drop_index(batch_op.f('ix_research_stages_project_id'))
        batch_op.drop_index(batch_op.f('ix_research_stages_id'))

    op.drop_table('research_stages')
    with op.batch_alter_table('research_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_memory_project_id'))
        batch_op.drop_index(batch_op.f('ix_research_memory_memory_type'))
        batch_op.drop_index(batch_op.f('ix_research_memory_id'))

    op.drop_table('research_memory')
    with op.batch_alter_table('research_gaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_gaps_project_id'))
        batch_op.drop_index(batch_op.f('ix_research_gaps_id'))

    op.drop_table('research_gaps')
    with op.batch_alter_table('literature_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_literature_papers_project_id'))
        batch_op.drop_index(batch_op.f('ix_literature_papers_id'))

    op.drop_table('literature_papers')
    with op.batch_alter_table('knowledge_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_nodes_project_id'))

    op.drop_table('knowledge_nodes')
    with op.batch_alter_table('knowledge_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_edges_target'))
        batch_op.drop_index(batch_op.f('ix_knowledge_edges_source'))
        batch_op.drop_index(batch_op.f('ix_knowledge_edges_project_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_edges_id'))

    op.drop_table('knowledge_edges')
    with op.batch_alter_table('hypotheses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hypotheses_project_id'))
        batch_op.drop_index(batch_op.f('ix_hypotheses_id'))

    op.drop_table('hypotheses')
    with op.batch_alter_table('generated_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_files_project_id'))
        batch_op.drop_index(batch_op.f('ix_generated_files_id'))

    op.drop_table('generated_files')
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_runs_id'))

    op.drop_table('experiment_runs')
    with op.batch_alter_table('experiment_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_plans_project_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_plans_id'))

    op.drop_table('experiment_plans')
    with op.batch_alter_table('dataset_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_recommendations_project_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_recommendations_id'))

    op.drop_table('dataset_recommendations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('agent_reach_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_reach_evidence_project_id'))
        batch_op.drop_index(batch_op.f('ix_agent_reach_evidence_id'))

    op.drop_table('agent_reach_evidence')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('billing_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_billing_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_billing_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_billing_transactions_reference_id'))
        batch_op.drop_index(batch_op.f('ix_billing_transactions_id'))

    op.drop_table('billing_transactions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('system_compute_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_compute_configs_id'))

    op.drop_table('system_compute_configs')
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_embeddings_id'))
        batch_op.drop_index(batch_op.f('ix_document_embeddings_doc_id'))
        batch_op.drop_index(batch_op.f('ix_document_embeddings_collection_name'))

    op.drop_table('document_embeddings')
    with op.batch_alter_table('api_key_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_configs_id'))

    op.drop_table('api_key_configs')
    # ### end Alembic commands ###
